<!DOCTYPE html><html lang="en"><head><x-page-head title="Statistics"/></head><body><div class="shell"><x-app-sidebar active="statistics"/><main><x-page-topbar/><div class="content statistics-page">
<section class="discovery-heading"><p class="eyebrow">YOUR INTERNET, BY THE NUMBERS</p><div class="heading"><div><h1>Personal trends</h1><p>Patterns across every account, service, post, and photograph in Afterfeed.</p></div></div></section>
<section class="stat-summary"><article><strong>{{ number_format($summary['posts']) }}</strong><span>posts & comments</span></article><article><strong>{{ number_format($summary['photos']) }}</strong><span>archived photos</span></article><article><strong>{{ number_format($summary['years']) }}</strong><span>years represented</span></article><article><strong>{{ number_format($summary['accounts']) }}</strong><span>social accounts</span></article></section>
<div class="stats-grid">
<section class="stat-panel wide"><header><div><p class="eyebrow">ACTIVITY</p><h2>Most active years</h2></div></header>@php($yearMax=max(1,(int)$years->max('total')))<div class="horizontal-bars">@foreach($years as $item)<div><b>{{ $item->label }}</b><i><span style="width:{{ ($item->total/$yearMax)*100 }}%"></span></i><strong>{{ number_format($item->total) }}</strong></div>@endforeach</div></section>
<section class="stat-panel"><header><div><p class="eyebrow">RHYTHM</p><h2>Posting by hour</h2></div></header>@php($hourMax=max(1,(int)$hours->max('total')))<div class="vertical-chart">@foreach($hours as $item)<div><i style="height:{{ ($item->total/$hourMax)*100 }}%" title="{{ $item->label }}:00 · {{ number_format($item->total) }} posts"></i><span>{{ $item->label%3===0?sprintf('%02d',$item->label):'' }}</span></div>@endforeach</div><p class="chart-caption">Hour of day · archive timestamps</p></section>
<section class="stat-panel"><header><div><p class="eyebrow">RHYTHM</p><h2>Posting by weekday</h2></div></header>@php($dayNames=['Sun','Mon','Tue','Wed','Thu','Fri','Sat'])@php($weekdayMax=max(1,(int)$weekdays->max('total')))<div class="weekday-chart">@foreach($weekdays as $item)<div><i><span style="height:{{ ($item->total/$weekdayMax)*100 }}%"></span></i><b>{{ $dayNames[$item->label] }}</b><small>{{ number_format($item->total) }}</small></div>@endforeach</div></section>
<section class="stat-panel wide"><header><div><p class="eyebrow">LANGUAGE</p><h2>Most-used words</h2></div><span>Common filler words removed</span></header>@php($wordMax=max(1,(int)$words->max('total')))<div class="word-cloud">@foreach($words as $word)<span style="font-size:{{ 12+($word->total/$wordMax)*22 }}px" title="{{ number_format($word->total) }} uses">{{ $word->label }}</span>@endforeach</div></section>
<section class="stat-panel"><header><div><p class="eyebrow">TOPICS</p><h2>Favorite hashtags</h2></div></header><div class="tag-ranking">@forelse($hashtags as $tag)<span><b>#{{ $tag->label }}</b><small>{{ number_format($tag->total) }}</small></span>@empty<p>No structured hashtags found.</p>@endforelse</div></section>
<section class="stat-panel"><header><div><p class="eyebrow">REDDIT</p><h2>Favorite communities</h2></div></header>@php($communityMax=max(1,(int)$communities->max('total')))<div class="rank-list">@forelse($communities as $item)<div><b>r/{{ $item->label }}</b><i><span style="width:{{ ($item->total/$communityMax)*100 }}%"></span></i><small>{{ number_format($item->total) }}</small></div>@empty<p>No Reddit communities found.</p>@endforelse</div></section>
<section class="stat-panel wide"><header><div><p class="eyebrow">PHOTOGRAPHY</p><h2>Photos per year</h2></div></header>@php($photoMax=max(1,(int)$photosByYear->max('total')))<div class="photo-history">@foreach($photosByYear as $item)<div><i style="height:{{ ($item->total/$photoMax)*100 }}%" title="{{ $item->label }} · {{ number_format($item->total) }} photos"></i><span>{{ $item->label }}</span></div>@endforeach</div></section>
<section class="stat-panel full"><header><div><p class="eyebrow">PLATFORMS</p><h2>Services used over time</h2></div></header>@php($serviceGroups=$serviceYears->groupBy('year'))<div class="service-history">@foreach($serviceGroups as $year=>$items)@php($total=$items->sum('total'))<div><b>{{ $year }}</b><i>@foreach($items as $item)<span data-service="{{ $item->platform }}" style="width:{{ ($item->total/$total)*100 }}%" title="{{ ucfirst($item->platform) }} · {{ number_format($item->total) }}"></span>@endforeach</i><small>{{ number_format($total) }}</small></div>@endforeach</div><div class="service-legend">@foreach($serviceYears->pluck('platform')->unique() as $service)<span data-service="{{ $service }}"><i></i>{{ ucfirst($service) }}</span>@endforeach</div></section>
<section class="stat-panel full"><header><div><p class="eyebrow">CONNECTIONS</p><h2>People interacted with most</h2></div><span>Mentions and direct-message participants</span></header>@php($peopleMax=max(1,(int)$people->max('total')))<div class="people-ranking">@foreach($people as $index=>$person)<div><em>{{ $index+1 }}</em><b>{{ $person->label }}</b><i><span style="width:{{ ($person->total/$peopleMax)*100 }}%"></span></i><small>{{ number_format($person->total) }}</small></div>@endforeach</div></section>
</div></div></main></div></body></html>
