<!DOCTYPE html><html lang="en"><head><x-page-head title="Post details"/></head><body><div class="shell"><x-app-sidebar active="timeline"/><main><x-page-topbar/><div class="content post-detail-page">
<a class="back-link" href="{{ url()->previous() }}">← Back</a>@if(session('status'))<div class="status-message">{{ session('status') }}</div>@endif
<article class="detail-post"><header><x-service-icon :platform="$post->socialAccount->platform"/><div><strong>{{ $post->socialAccount->display_name ?: $post->socialAccount->handle }}</strong><span>{{ $post->socialAccount->handle }} · {{ $post->posted_at?->format('F j, Y g:i A') }}</span></div><div class="detail-post-actions"><button class="share-image-trigger" type="button" data-open-share-card>Share as image</button>@if($post->originalUrl())<a href="{{ $post->originalUrl() }}" target="_blank" rel="noreferrer">Original ↗</a>@endif</div></header><x-post-body :post="$post"/><x-post-context :post="$post"/>@if($post->attachments->isNotEmpty())<div class="detail-media">@foreach($post->attachments as $media)@if($media->type==='video')<video controls data-lightbox data-media-type="video" data-media-src="{{ asset('storage/'.$media->path) }}"><source src="{{ asset('storage/'.$media->path) }}"></video>@else<img src="{{ asset('storage/'.$media->path) }}" alt="{{ $media->alt_text ?: 'Archived image' }}" data-lightbox data-media-type="image" data-media-src="{{ asset('storage/'.$media->path) }}">@endif @endforeach</div>@endif</article>
@php($shareImage=$post->attachments->firstWhere('type','image'))
@php($shareData=['body'=>$post->body ?: ($post->type==='boost' ? 'Boosted a post' : ''),'name'=>$post->socialAccount->display_name ?: $post->socialAccount->handle,'handle'=>$post->socialAccount->handle,'platform'=>$post->socialAccount->platform,'date'=>$post->posted_at?->format('F j, Y'),'year'=>$post->posted_at?->format('Y'),'image'=>$shareImage ? asset('storage/'.$shareImage->path) : null])
<dialog class="share-card-dialog" data-share-card-dialog>
<div class="share-card-heading"><div><p class="eyebrow">SHARE A MEMORY</p><h2>Share as an image</h2><p>Create a portable PNG without publishing or linking to Afterfeed.</p></div><button type="button" data-close-share-card aria-label="Close share image creator">×</button></div>
<div class="share-card-workspace" id="share-card-generator"><div class="share-card-preview"><canvas aria-label="Preview of shareable post image"></canvas><p data-share-status aria-live="polite">Everything is rendered locally in your browser.</p></div><form class="share-card-controls" onsubmit="return false">
<fieldset><legend>Shape</legend><div class="share-shapes"><label><input type="radio" name="share_shape" value="square" checked><span>Square<small>1080 × 1080</small></span></label><label><input type="radio" name="share_shape" value="portrait"><span>Portrait<small>1080 × 1350</small></span></label><label><input type="radio" name="share_shape" value="landscape"><span>Landscape<small>1200 × 675</small></span></label></div></fieldset>
<fieldset><legend>Include</legend><div class="share-options"><label><input type="checkbox" name="share_identity" checked><span>Name and handle</span></label><label><input type="checkbox" name="share_platform" checked><span>Original platform</span></label><label><input type="checkbox" name="share_date" checked><span>Full original date</span></label><label><input type="checkbox" name="share_footer" checked><span>“From my archive”</span></label>@if($shareImage)<label><input type="checkbox" name="share_media" checked><span>Archived photo</span></label>@endif</div></fieldset>
<div class="share-card-buttons"><button class="share-download" type="button" data-download-share-card>Download PNG</button><button type="button" data-copy-share-card>Copy image</button></div>
</form></div>
<script type="application/json" data-share-card-data>@json($shareData)</script>
</dialog>
<div class="post-tools"><section><h2>Your annotation</h2><form class="annotation-form" method="post" action="{{ route('posts.annotation.update',$post) }}">@csrf @method('PUT')<label>Private note<textarea name="note" rows="5" placeholder="Why does this matter to you?">{{ $post->annotation?->note }}</textarea></label><label>Tags<input name="tags" value="{{ implode(', ', $post->annotation?->tags??[]) }}" placeholder="family, favorite trip, old web"></label><div class="location-fields"><label>Place name<input name="place_name" value="{{ $post->annotation?->place_name }}" placeholder="Yellowstone National Park"></label><label>Latitude<input name="latitude" type="number" step="any" min="-90" max="90" value="{{ $post->annotation?->latitude }}"></label><label>Longitude<input name="longitude" type="number" step="any" min="-180" max="180" value="{{ $post->annotation?->longitude }}"></label></div><div class="check-row"><label><input type="checkbox" name="favorite" value="1" @checked($post->annotation?->favorite)> Favorite</label><label><input type="checkbox" name="hidden" value="1" @checked($post->annotation?->hidden)> Hide from normal browsing</label></div><button>Save annotation</button></form></section>
<section><h2>Add to a collection</h2><div class="collection-actions">@forelse($collections as $collection)@if($post->collections->contains($collection))<form method="post" action="{{ route('collections.posts.destroy',[$collection,$post]) }}">@csrf @method('DELETE')<button class="included">✓ {{ $collection->name }} <small>Remove</small></button></form>@else<form method="post" action="{{ route('collections.posts.store',[$collection,$post]) }}">@csrf<button>＋ {{ $collection->name }}</button></form>@endif @empty<p>No collections yet. <a href="{{ route('collections.index') }}">Create one</a>.</p>@endforelse</div></section></div>
</div></main></div></body></html>
