server {
    listen 80;
    server_name _;
    root /var/www/html/public;
    index index.php;

    client_max_body_size 6m;

    location / {
        try_files $uri $uri/ /index.php?$query_string;
    }

    location ~ \.php$ {
        include fastcgi_params;
        fastcgi_param SCRIPT_FILENAME /var/www/html/public/index.php;
        fastcgi_param SCRIPT_NAME /index.php;
        fastcgi_param HTTP_PROXY "";
        fastcgi_read_timeout 3600s;
        fastcgi_send_timeout 3600s;
        fastcgi_pass afterfeed:9000;
    }

    location ~ /\. {
        deny all;
    }
}
