<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Media — Afterfeed</title><meta name="description" content="Browse media from your social archives."><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="theme-color" content="#375d4a"><link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml"><link rel="icon" href="{{ asset('favicon-32.png') }}" sizes="32x32" type="image/png"><link rel="apple-touch-icon" href="{{ asset('apple-touch-icon.png') }}"><link rel="manifest" href="{{ asset('site.webmanifest') }}">
@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body><div class="shell">
<x-app-sidebar active="media"/>
<main><header class="topbar"><button class="menu" aria-label="Menu">☰</button><form class="search" method="get" action="{{ route('archives.index') }}#timeline">⌕<input name="q" type="search" placeholder="Search your digital past…" aria-label="Search"><kbd>↵</kbd></form><button class="primary" id="import-button" type="button">＋ Import archive</button><input id="archive-file" type="file" accept=".zip,.tar.gz,.tgz,application/zip,application/gzip" hidden></header>
<div id="upload-panel" class="upload-panel" hidden><div><strong id="upload-title">Uploading archive…</strong><span id="upload-detail">Preparing upload</span></div><progress id="upload-progress" max="100" value="0"></progress><button id="upload-cancel" type="button">Cancel</button></div>
<div class="content media-page"><section class="media-heading"><p class="eyebrow">THE VISUAL ARCHIVE</p><div class="heading"><div><h1>All your media</h1><p>Photos and videos from every imported account, together in one place.</p></div><span>{{ number_format($media->total()) }} items</span></div></section>
<form class="media-filters" method="get"><label>Account<select name="account"><option value="">All accounts</option>@foreach($accounts as $account)<option value="{{ $account->id }}" @selected(request('account')==$account->id)>{{ ucfirst($account->platform) }} · {{ $account->handle }}</option>@endforeach</select></label><label>Media type<select name="type"><option value="">Photos & videos</option><option value="image" @selected(request('type')==='image')>Photos</option><option value="video" @selected(request('type')==='video')>Videos</option></select></label><button type="submit">Apply filters</button>@if(request('account')||request('type'))<a href="{{ route('media.index') }}">Clear</a>@endif</form>
<section class="media-gallery">@forelse($media as $attachment)@php($post=$attachment->post)@php($account=$post->socialAccount)@php($mediaLink=$post->originalUrl() ?: $post->sharedUrl())<article class="media-tile">@if($attachment->type==='video')<video controls preload="metadata" data-lightbox data-media-type="video" data-media-src="{{ asset('storage/'.$attachment->path) }}" aria-label="Open archived video"><source src="{{ asset('storage/'.$attachment->path) }}"></video>@else<img src="{{ asset('storage/'.$attachment->path) }}" alt="{{ $attachment->alt_text ?: 'Archived image' }}" loading="lazy" data-lightbox data-media-type="image" data-media-src="{{ asset('storage/'.$attachment->path) }}">@endif<div class="media-caption"><x-service-icon :platform="$account->platform"/><div><strong>{{ $account->display_name ?: $account->handle }}</strong><time>{{ $post->posted_at?->format('M j, Y') }}</time></div>@if($mediaLink)<a href="{{ $mediaLink }}" target="_blank" rel="noreferrer" aria-label="{{ $post->originalUrl() ? 'Open original post' : 'Open shared link' }}">↗</a>@endif</div></article>@empty<div class="empty media-empty"><div class="spark">▧</div><h3>No media found</h3><p>Try another filter or import an archive containing photos or videos.</p></div>@endforelse</section>
<x-pagination :paginator="$media" previous="← Newer" next="Older →"/>
</div></main></div></body></html>
