<!DOCTYPE html>
<html lang="en"><head><meta charset="UTF-8"><meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Afterfeed — Your internet, remembered</title><meta name="description" content="Browse your social archives in one private place."><meta name="csrf-token" content="{{ csrf_token() }}"><meta name="theme-color" content="#375d4a"><link rel="icon" href="{{ asset('favicon.svg') }}" type="image/svg+xml"><link rel="icon" href="{{ asset('favicon-32.png') }}" sizes="32x32" type="image/png"><link rel="apple-touch-icon" href="{{ asset('apple-touch-icon.png') }}"><link rel="manifest" href="{{ asset('site.webmanifest') }}">
@vite(['resources/css/app.css', 'resources/js/app.js'])</head>
<body><div class="shell">
<x-app-sidebar active="timeline"/>
<main><header class="topbar"><button class="menu" aria-label="Menu">☰</button><form class="search" method="get" action="{{ route('archives.index') }}#timeline">⌕<input name="q" type="search" value="{{ $search }}" placeholder="Search your digital past…" aria-label="Search">@foreach(['account','year','month','type','media'] as $parameter)@if(request($parameter))<input type="hidden" name="{{ $parameter }}" value="{{ request($parameter) }}">@endif @endforeach<kbd>↵</kbd></form><button class="primary" id="import-button" type="button">＋ Import archive</button><input id="archive-file" type="file" accept=".zip,.tar.gz,.tgz,application/zip,application/gzip" hidden></header>
<div id="upload-panel" class="upload-panel" hidden><div><strong id="upload-title">Uploading archive…</strong><span id="upload-detail">Preparing upload</span></div><progress id="upload-progress" max="100" value="0"></progress><button id="upload-cancel" type="button">Cancel</button></div>
<div class="content">@if(!request()->filled('account'))<section class="hero"><p class="eyebrow">YOUR PERSONAL INTERNET ARCHIVE</p><h1>Everything you shared,<br><em>all in one place.</em></h1><p>Explore years of posts, photos, conversations, and small moments—without the noise of the feed.</p></section>@endif
@if($profile)<section class="profile-card">@if($profile->header_path)<div class="profile-cover" style="background-image:url('{{ asset('storage/'.$profile->header_path) }}')"></div>@endif<div class="profile-main">@if($profile->avatar_path)<img class="profile-avatar" src="{{ asset('storage/'.$profile->avatar_path) }}" alt="{{ $profile->display_name }} profile picture">@else<div class="profile-avatar fallback">{{ strtoupper(substr($profile->display_name,0,1)) }}</div>@endif<div class="profile-copy"><h2>{{ $profile->display_name }} @if($profile->verified)<span title="Verified">✓</span>@endif</h2><p class="handle">{{ $profile->handle }}</p><p>{{ $profile->bio }}</p>@if($profile->location||$profile->website)<small>{{ $profile->location }} @if($profile->website) · <a href="{{ $profile->website }}">{{ $profile->website }}</a>@endif</small>@endif</div><div class="profile-stats"><span><strong>{{ number_format($profile->posts_count) }}</strong> posts</span><span><strong>{{ number_format($profile->liked_posts_count) }}</strong> likes</span><span><strong>{{ number_format($connectionCounts['following']??0) }}</strong> following</span><span><strong>{{ number_format($connectionCounts['follower']??0) }}</strong> followers</span></div></div></section>@endif
@if(!request()->filled('account'))<section><div class="heading"><div><p class="eyebrow">SOURCES</p><h2>Your archives</h2></div><span>{{ $archives->count() }} connected</span></div>
<div class="source-grid">@forelse($archives as $archive)
<a class="source" href="{{ route('archives.index',['account'=>$archive->social_account_id]) }}" data-platform="{{ $archive->socialAccount->platform }}"><x-service-icon :platform="$archive->socialAccount->platform" class="icon"/><div class="source-copy"><h3>{{ $archive->socialAccount->display_name ?: ucfirst($archive->socialAccount->platform) }}</h3><p>{{ $archive->socialAccount->handle ?: $archive->label }}</p></div><div class="count"><strong>{{ number_format($archive->posts_count) }}</strong><small>items</small></div></a>
@empty @foreach(['facebook','x','reddit','bluesky','mastodon','instagram','google_plus','livejournal'] as $platform)
<article class="source muted" data-platform="{{ $platform }}"><x-service-icon :platform="$platform" class="icon"/><div class="source-copy"><h3>{{ $platform==='x'?'Twitter / X':($platform==='google_plus'?'Google+':ucfirst($platform)) }}</h3><p>Ready to import</p></div><b class="add">＋</b></article>
@endforeach @endforelse</div></section>@endif
<section id="timeline" class="timeline"><div class="heading"><div><p class="eyebrow">MEMORY LANE</p><h2>Your timeline</h2></div><span>{{ number_format($timelinePosts->total()) }} moments</span></div>
@php($accountQuery=request('account')?['account'=>request('account')]:[])@php($dateQuery=array_filter(['year'=>$year,'month'=>$month,'day'=>$day]))@php($searchQuery=$search?['q'=>$search]:[])
<div class="timeline-tools"><form class="date-filters" method="get" action="{{ route('archives.index') }}#timeline">@if(request('account'))<input type="hidden" name="account" value="{{ request('account') }}">@endif @if(request('type'))<input type="hidden" name="type" value="{{ request('type') }}">@endif @if(request('media'))<input type="hidden" name="media" value="1">@endif @if($search)<input type="hidden" name="q" value="{{ $search }}">@endif<label>Year<select name="year"><option value="">All years</option>@foreach($timelineYears as $availableYear)<option value="{{ $availableYear }}" @selected((string)$year===(string)$availableYear)>{{ $availableYear }}</option>@endforeach</select></label><label>Month<select name="month"><option value="">All months</option>@foreach(range(1,12) as $availableMonth)<option value="{{ $availableMonth }}" @selected($month===$availableMonth)>{{ Carbon\CarbonImmutable::create(2000,$availableMonth)->format('F') }}</option>@endforeach</select></label><button type="submit">Apply date</button>@if($year||$month)<a class="clear-date" href="{{ route('archives.index',[...$accountQuery,...$searchQuery,...array_filter(['type'=>request('type'),'media'=>request('media')])]) }}#timeline">Clear date</a>@endif</form>
<nav class="filters"><a @class(['selected'=>!request('type')&&!request('media')]) href="{{ route('archives.index',[...$accountQuery,...$dateQuery,...$searchQuery]) }}#timeline">Everything</a><a @class(['selected'=>request('type')==='post']) href="{{ route('archives.index',[...$accountQuery,...$dateQuery,...$searchQuery,'type'=>'post']) }}#timeline">Posts</a><a @class(['selected'=>request('type')==='reply']) href="{{ route('archives.index',[...$accountQuery,...$dateQuery,...$searchQuery,'type'=>'reply']) }}#timeline">Replies</a><a @class(['selected'=>request('type')==='retweet']) href="{{ route('archives.index',[...$accountQuery,...$dateQuery,...$searchQuery,'type'=>'retweet']) }}#timeline">Retweets</a><a @class(['selected'=>request('type')==='boost']) href="{{ route('archives.index',[...$accountQuery,...$dateQuery,...$searchQuery,'type'=>'boost']) }}#timeline">Boosts</a><a @class(['selected'=>request('media')]) href="{{ route('archives.index',[...$accountQuery,...$dateQuery,...$searchQuery,'media'=>1]) }}#timeline">With media</a>@if($search)<a class="clear-search" href="{{ route('archives.index',[...$accountQuery,...$dateQuery]) }}#timeline">Clear “{{ Str::limit($search,25) }}”</a>@endif</nav></div>
@forelse($timelinePosts as $post)<article class="post-card">
<header>@if($post->socialAccount->avatar_path)<img class="avatar" src="{{ asset('storage/'.$post->socialAccount->avatar_path) }}" alt="">@else<div class="avatar">{{ strtoupper(substr(ltrim($post->socialAccount->handle,'@'),0,1)) }}</div>@endif<div><strong>{{ $post->socialAccount->display_name }}</strong><span>{{ $post->socialAccount->handle }}</span></div><x-service-icon :platform="$post->socialAccount->platform" class="post-service"/><time datetime="{{ $post->posted_at?->toAtomString() }}">{{ $post->posted_at?->format('M j, Y') }}</time></header>
@if(data_get($post->metadata,'content_warning')||data_get($post->metadata,'sensitive'))<details class="content-warning"><summary>{{ data_get($post->metadata,'content_warning') ?: 'Sensitive content — show post' }}</summary>@endif<x-post-body :post="$post" class="post-body"/><x-post-context :post="$post"/>
@if($post->attachments->isNotEmpty())<div @class(['media-grid','multi'=>$post->attachments->count()>1])>@foreach($post->attachments->take(4) as $attachment) @if($attachment->type==='video')<video controls preload="metadata" data-lightbox data-media-type="video" data-media-src="{{ asset('storage/'.$attachment->path) }}" aria-label="Open archived video"><source src="{{ asset('storage/'.$attachment->path) }}"></video>@else<img src="{{ asset('storage/'.$attachment->path) }}" alt="{{ $attachment->alt_text ?: 'Archived image from this post' }}" loading="lazy" data-lightbox data-media-type="image" data-media-src="{{ asset('storage/'.$attachment->path) }}">@endif @endforeach</div>@endif
@if(data_get($post->metadata,'content_warning')||data_get($post->metadata,'sensitive'))</details>@endif
<footer>@if($post->deleted_at)<span class="deleted">Deleted {{ $post->deleted_at->format('M Y') }}</span>@else<span class="post-type">{{ $post->type==='retweet'?'↻':($post->type==='reply'?'↩':'✦') }} {{ ucfirst($post->type) }}</span>@endif @if(array_key_exists('favorite_count',$post->metadata??[]))<span>♡ {{ number_format(data_get($post->metadata,'favorite_count',0)) }}</span>@endif @if(array_key_exists('retweet_count',$post->metadata??[]))<span>↻ {{ number_format(data_get($post->metadata,'retweet_count',0)) }}</span>@endif<a href="{{ route('posts.show',$post) }}">Annotate / collect</a>@if($post->originalUrl())<a href="{{ $post->originalUrl() }}" target="_blank" rel="noreferrer">Original ↗</a>@endif</footer></article>
@empty<div class="empty"><div class="spark">✦</div><h3>No moments found</h3><p>Try another filter or import an archive to fill your timeline.</p></div>@endforelse
<x-pagination :paginator="$timelinePosts" previous="← Newer" next="Older →" fragment="#timeline"/></section>
</div></main></div></body></html>
