<!DOCTYPE html><html lang="en"><head><x-page-head title="Settings"/></head><body><div class="shell"><x-app-sidebar active="settings"/><main><x-page-topbar/><div class="content settings-page">
<section class="discovery-heading"><p class="eyebrow">MAKE AFTERFEED YOURS</p><div class="heading"><div><h1>Settings</h1><p>Local preferences, privacy defaults, and installation diagnostics.</p></div></div></section>
@if(session('status'))<div class="status-message">{{ session('status') }}</div>@endif
<form method="post" action="{{ route('settings.update') }}" class="settings-form">@csrf @method('PUT')
<section class="settings-card"><header><div><h2>Display</h2><p>Control how dates and the main timeline appear.</p></div></header><div class="settings-fields"><label><span>Timezone<small>Used when displaying archive timestamps.</small></span><select name="timezone">@foreach($timezones as $timezone)<option value="{{ $timezone }}" @selected($values['timezone']===$timezone)>{{ str_replace('_',' ',$timezone) }}</option>@endforeach</select></label><label><span>Timeline page size<small>Number of cards loaded on each page.</small></span><select name="timeline_per_page">@foreach([12,18,24,36,48] as $size)<option value="{{ $size }}" @selected($values['timeline_per_page']===$size)>{{ $size }} posts</option>@endforeach</select></label></div></section>
<section class="settings-card"><header><div><h2>Name privacy</h2><p>Hide former names throughout Afterfeed without changing the original archive.</p></div></header><div class="name-privacy"><label class="privacy-switch"><input type="checkbox" name="privacy_hide_deadnames" value="1" @checked($values['privacy_hide_deadnames'])><span><strong>Hide my deadnames</strong><small>Applies to pages, search results, API and MCP responses, and every export format.</small></span></label><label class="name-mapping-field"><span>Name replacements<small>Enter one mapping per line as <code>former name =&gt; current name</code>. Each identity can have a different replacement.</small></span><textarea name="privacy_name_mappings" rows="7" autocomplete="off" placeholder="Former IRL name => Current IRL name&#10;Former fandom name => Current fandom name">{{ collect($values['privacy_name_mappings'])->map(fn($mapping) => $mapping['from'].' => '.$mapping['to'])->implode("\n") }}</textarea></label><p>Matching is case-insensitive. Leave the right side empty to remove that name. Original imported files and database values stay untouched.</p></div></section>
<section class="settings-card"><header><div><h2>Export privacy</h2><p>Defaults shown whenever you export a collection.</p></div></header><div class="settings-toggles"><label><input type="checkbox" name="default_export_strip_metadata" value="1" @checked($values['default_export_strip_metadata'])><span><strong>Strip metadata by default</strong><small>Remove raw platform metadata and re-encode media without EXIF.</small></span></label><label><input type="checkbox" name="default_export_include_links" value="1" @checked($values['default_export_include_links'])><span><strong>Include original links by default</strong><small>Links can reveal account and post identifiers to export recipients.</small></span></label></div></section>
<button class="settings-save">Save settings</button></form>
<section class="settings-card"><header><div><h2>API & MCP access</h2><p>Create bearer tokens for integrations. Tokens only access your archive.</p></div></header>
@if(session('new_api_token'))<div class="token-reveal"><strong>Copy this token now—it will not be shown again.</strong><code>{{ session('new_api_token') }}</code></div>@endif
<form method="post" action="{{ route('tokens.store') }}" class="token-create">@csrf<input name="name" required maxlength="80" placeholder="My MCP client"><button>Create token</button></form>
<div class="token-list">@forelse(auth()->user()->tokens()->latest()->get() as $token)<div><span><strong>{{ $token->name }}</strong><small>{{ $token->last_used_at ? 'Last used '.$token->last_used_at->diffForHumans() : 'Never used' }}</small></span><form method="post" action="{{ route('tokens.destroy',$token) }}">@csrf @method('DELETE')<button>Revoke</button></form></div>@empty<p>No API tokens yet.</p>@endforelse</div></section>
<section class="settings-card diagnostics-card"><header><div><h2>Installation</h2><p>Read-only details useful when configuring or troubleshooting Afterfeed.</p></div></header><dl><div><dt>Database</dt><dd>{{ strtoupper($diagnostics['database']) }}</dd></div><div><dt>PHP</dt><dd>{{ $diagnostics['php'] }}</dd></div><div><dt>Laravel</dt><dd>{{ $diagnostics['laravel'] }}</dd></div><div><dt>Remote MCP</dt><dd><i @class(['enabled'=>$diagnostics['remote_mcp']])></i>{{ $diagnostics['remote_mcp'] ? 'Token ready' : 'No token' }}</dd></div><div><dt>MCP endpoint</dt><dd><code>{{ $diagnostics['mcp_endpoint'] }}</code></dd></div><div><dt>Allowed browser origins</dt><dd><code>{{ $diagnostics['allowed_origins'] ?: 'Not configured' }}</code></dd></div></dl>@unless($diagnostics['remote_mcp'])<p class="settings-help">Create a per-user token above before connecting a remote API or MCP client.</p>@endunless</section>
</div></main></div></body></html>
